### ISSUE TITLE
Does't work at all with HA 2024.8.0 - even with local docker

### ISSUE THREAD

**Issue by egg02** [ualex73/monitor_docker#158] opened 2024-08-08 07:24 UTC
`binary_sensor.docker_hub_update_available`  and `sensor.docker_hub` are available, but nothing else.

Any workaraounds?

**Comment by ualex73** [comment] 2024-08-08 07:50
Solution is to modify docker daemon to listen on a localhost port (my Home Assistant container uses the `host` network), restart docker daemon, then configure the `url` key in monitor_docker config.

https://docs.docker.com/config/daemon/remote-access/

```
[andrew~]$ cat /etc/docker/daemon.json 
{
  "hosts": ["unix:///var/run/docker.sock", "tcp://127.0.0.1:2375"]
}
```

configuration.yaml:
```
monitor_docker:
  url: "http://localhost:2375"
```

**Comment by egg02** [comment] 2024-08-08 08:43
That didn't work for me.

I'm running docker on a QNAP NAS (Container Station). Maybe things are different there.

`/etc/docker/daemon.json` didn't exist, I had to create it.

Probably it's better for me to wait for HA 2024.8.1; I don't want to ruin my Container Station setup.

**Comment by walk0080** [comment] 2024-08-08 15:03
Not working for me either (sudo systemctl edit docker.service).
Have Docker on Debian Linux.
My HA is in Docker w/ nginxproxymanager (not host network).

**Comment by nobodyspecial** [comment] 2024-08-08 16:03
Same here.

**Comment by egg02** [comment] 2024-08-08 16:46
> …  You also have to tell docker daemon to use it.

That doesn‘t help me.  As I mentioned before, my docker is running on a NAS. There is no systemd and no systemctl.

**Comment by adorobis** [comment] 2024-08-08 16:47
> Solution is to modify docker daemon

But why has this changed? I'm using macvlan network and I had to add additional bridge network to my container to be able to reach the host from it. Before 2024.8.0 it worked all ok probably via the sock connection which is exposed to HA.

**Comment by ualex73** [comment] 2024-08-08 16:52
> > Solution is to modify docker daemon
> 
> But why has this changed? I'm using macvlan network and I had to add additional bridge network to my container to be able to reach the host from it. Before 2024.8.0 it worked all ok probably via the sock connection which is exposed to HA.

We did not change it, but the underlying aiohttp currently does not support unix:// sockets anymore. We cannot downgrade it ourselves (or patch it), because it is part of the HA software.

**Comment by adorobis** [comment] 2024-08-08 16:57
Ok, thanks for explanation!

**Comment by andreasbrett** [comment] 2024-08-08 19:17
Should be fixed in HA 2024.8.1. Latest release of aiohttp fixes the root cause. 

https://github.com/home-assistant/core/pull/123394

**Comment by andreasbrett** [comment] 2024-08-08 19:21
This is pretty dangerous since that way access to Docker is exposed to any user on the Docker host. 

> Solution is to modify docker daemon to listen on a localhost port (my Home Assistant container uses the `host` network), restart docker daemon, then configure the `url` key in monitor_docker config.
> 
> https://docs.docker.com/config/daemon/remote-access/
> 
> ```
> $ cat /etc/docker/daemon.json 
> {
>   "hosts": ["unix:///var/run/docker.sock", "tcp://127.0.0.1:2375"]
> }
> ```
> 
> configuration.yaml:
> ```
> monitor_docker:
>   url: "http://localhost:2375"
> ```

**Comment by ualex73** [comment] 2024-08-09 18:11
Workaround is to do the following:
docker exec -it homeassistant /bin/bash
pip3 install --upgrade aiohttp

And restart HA ... or wait on 2024.8.1 ... It contains the fix.

**Comment by walk0080** [comment] 2024-08-09 18:42
> Workaround is to do the following: docker exec -it homeassistant /bin/bash pip3 install --upgrade aiohttp
> 
> And restart HA

Worked for me, thank you.

**Comment by egg02** [comment] 2024-08-09 19:14
> Worked for me, thank you.

Yep, for me, too.

Thanks!

**Comment by xraver** [comment] 2024-08-09 19:55
> > Worked for me, thank you.
> 
> Yep, for me, too.
> 
> Thanks!

same here! thanks

**Comment by ualex73** [comment] 2024-08-10 19:14
HA 2024.8.1 is out, so please upgrade to that one.

**Comment by adorobis** [comment] 2024-08-10 20:38
Great, works again with sockets. Many thanks!

**Comment by madmic1314** [comment] 2024-08-10 20:40
World with no chances after upgrade to 2024.8.1

**Comment by ualex73** [comment] 2024-08-11 10:19
Ok, let's leave this issue open for a few days for other people to read it, afterwards we will close it.

**Closed** 2024-08-21 20:22 UTC
