### ISSUE TITLE
Enhancement request - Docker compose sensor 

### ISSUE THREAD

**Issue by tamimology** [ualex73/monitor_docker#88] opened 2021-12-29 10:48 UTC
There is a sensor for docker version
I believe it would be a good idea to have an optional sensor for docker-compose version, as well as check for the latest version of both

**Comment by ualex73** [comment] 2021-12-29 12:10
The problem is that the docker-compose version is not available in the Docker API (it is an external thing). Checking for latest version, goes a bit past the purpose of the monitor_docker (and it is not easy to build in to this custom component) ... If you want to check for the latest versions, there are multiple sites which can send you e.g. an email about it.

**Comment by tamimology** [comment] 2021-12-29 22:37
Fair enough. For the version check i meant for the docker itself not containers (same for docker-compose).

Other than that this custome component is the best for docker on the web. Really.

Thanks Alex for your work

**Comment by ualex73** [comment] 2024-05-23 19:48
Closing it, it is an old one.

**Closed by ualex73** 2024-05-23 19:48 UTC
