### ISSUE TITLE
Recreating a docker container causes errors looking for old one until reboot

### ISSUE THREAD

**Issue by bartowski1182** [ualex73/monitor_docker#122] opened 2023-04-21 20:19 UTC
When I bring a docker container down and back up, I see my logs spammed with:

2023-04-21 16:16:03.098 ERROR (Thread-2 (RunDocker)) [custom_components.monitor_docker.helpers] [Docker] teslamate_teslamate_1: Container not available anymore (3) (DockerError(404, 'No such container: bc556f452791ea270bf943e754ba42a4c55426700f7997113be784fc7b4a8772'))

The annoying part is that the sensors are updated fine and are able to bind to the new docker container, despite the errors in the logs. Can we either get a fix for this or a way restart the monitor_docker integration?

**Comment by AlexKusnezov** [comment] 2023-05-17 13:09
same here, thanks for pointing it out

**Comment by derekoharrow** [comment] 2023-05-19 10:38
Duplicate of #104 

I've raised a new request (#124) asking to add a reload capability which would at least avoid the need to restart HA.

**Comment by ualex73** [comment] 2024-05-17 20:04
Can you test the latest version, I believe it is fixed in this one. If confirmed, I will make a new version.

**Comment by derekoharrow** [comment] 2024-05-18 09:30
Looking good so far. I have only been running it for about 30 minutes, but have killed and re-created some containers and it seems to be ok.

**Comment by ualex73** [comment] 2024-05-18 17:21
Sounds like a good test 👍

**Comment by ualex73** [comment] 2024-05-25 15:38
No negative response, so I will close this ticket :-) if it happens again, please raise a new ticket with info.

**Closed by ualex73** 2024-05-25 15:38 UTC
